### ISSUE TITLE
请问你这个和CoreLock怎么好像啊

### ISSUE THREAD

**Issue by liuxuan30** [iosdeveloperpanc/PCGestureUnlock#2]
请问你这个和CoreLock怎么好像啊

**Comment by iosdeveloperpanc** [comment]
因为是参考了冯成林的coreLock，为了更面向实际开发，更全面的实现当初支付的功能，主要采用工厂模式封装出面向实际开发的GestureUnlock手势解锁终结者

**Comment by liuxuan30** [comment]
倒是添加了几个我需要的功能, 做的挺好的!
