### ISSUE TITLE
引用时候出错的问题

### ISSUE THREAD

**Issue by wangkedev** [iosdeveloperpanc/PCGestureUnlock#7]
应用到自己的项目中去的时候，PCCircleView.m文件中， 对数组最后一个对象的处理 方法报错
- (void)circleSetLastObjectWithState:(CircleState)state
  {
  [[self.circleSet lastObject] setState:state];
  }

错误提示：

Multiple methods named 'setState:' found with mismatched result ,parameter type or arrtibutes

**Comment by FelixBubble** [comment]
和MJRefresh同时使用的时候就会出现这个问题，求解决办法！
