### ISSUE TITLE
所谓的跳跃连线，其实根本就不跳跃

### ISSUE THREAD

**Issue by semnyqu** [iosdeveloperpanc/PCGestureUnlock#9]
哎，本来看这个代码架构还比较合理，觉得可以使用，后面发现这个明显的bug存在，跳跃连线根本做不到；动画中的跳跃连线，根本就没跳跃

**Comment by iosdeveloperpanc** [comment]
你是第一个这么说的，代码不会骗人，那个截图也不会骗人……

**Comment by semnyqu** [comment]
没跳跃的意思是 没有跳过两个圆圈中间的圆圈

**Comment by iosdeveloperpanc** [comment]
我特地做的这个功能，以前支付宝就是不允许用户跳跃画线，连线中间的圆圈都会连进来

**Comment by Joneze** [comment]
其实应该给个接口 让大伙可以开关这个跳跃条件。毕竟有些产品就是说 我要可以跳跃
